just name
chingu-voyages/v47-tier1-team-03 pull request #81
Opened 2024-02-14 17:34 UTC by Diaaana03

2024-02-14 19:42 UTC, cris-valente requested changes
Please refer to our [Figma design](https://www.figma.com/file/Z1sSZYngU1YoNi6HnfktuP/Voyage-47---Team-3?type=design&node-id=262-2677&mode=design&t=IX8ds88OORKeuXoq-0), Diana. I made a few comments on each line

2024-02-16 00:18 UTC, Diaaana03 commented on styles.css
> +  font-size: 1.4rem;
done

2024-02-16 00:21 UTC, Diaaana03 reviewed
done

2024-02-16 17:39 UTC, Morais-C approved these changes

2024-02-16 17:40 UTC, Morais-C approved these changes

2024-02-16 18:23 UTC, cris-valente approved these changes
Nice! Approved.

2024-02-16 18:23 UTC, merged